"""add content column to contract

Revision ID: aa0fcb2744f6
Revises:
Create Date: 2026-06-26 21:46:20.120040

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "aa0fcb2744f6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
